# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Devfile integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # every day at 9am EST
    - cron: 0 1 * * *

jobs:
  test_with_minikube_linux:
    name: Run tests
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Linux - Setup Minikube
        if: matrix.os == 'ubuntu-latest'
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
            minikube version: 'v1.21.0'
            kubernetes version: 'v1.21.0'
            driver: 'docker'
            github token: ${{ secrets.GITHUB_TOKEN }}
            start args: '--addons=ingress'

      - name: MacOS - Setup Minikube
        if: matrix.os == 'macos-10.15'
        uses: medyagh/setup-minikube@latest
        with:
          container-runtime: containerd

      - name: Install ODO
        uses: redhat-actions/openshift-tools-installer@v1
        with:
            # Installs the latest release of odo
            odo: "latest"

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.9"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Run test with pipenv and pytest
        run: |
          odo version
          pipenv install --dev
          pipenv run pytest tests -v
