#
#   Copyright 2021-2022 Red Hat, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
name: Devfile integration tests (latest Odo build)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # every day at 9am EST
    - cron: 0 1 * * *

jobs:
  test_with_minikube:
    name: Run tests
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11 ]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    timeout-minutes: 20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check out the latest odo repository code
        uses: actions/checkout@v3
        with:
          repository: redhat-developer/odo
          ref: main
          path: odo

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.3'
      - run: go version

      # Build and installs odo from source code
      - name: Build and Install ODO
        run: |
          cd odo
          make goget-tools
          make bin
          mv ./odo /usr/local/bin/odo
          cd ..
          rm -rf odo

      # Setup Python
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: "3.9.10"

      - name: Run test with pipenv and pytest
        run: |
          odo version
          pipenv run pytest tests/odo_300 -v

